manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: nihalmeti
    #   url-base: https://github.com/nihalmeti
    - name: SamIAm2000
      url-base: https://github.com/SamIAm2000
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml 
    # - name: nice-view-gem #new entry
    #   remote: nihalmeti #new entry
    #   revision: main #new entry
    - name: zmk
      remote: SamIAm2000
      revision: bongo-cat-dedicated-work-queue
  self:
    path: config
